### ISSUE TITLE
using for hands/arms only

### ISSUE THREAD

**Issue by Thibaut-HITLab** [oculus-samples/Unity-DepthAPI#10]
Hey, would this be possible to use this to have only hands/arms occlusion. not other objects

**Comment by TudorJude** [comment]
Hey Thibaut,

Yes, we will add a feature soon to this repo that will let you do that.

**Comment by TudorJude** [comment]
I misunderstood what you meant, my bad. I was thinking of a different feature. There should be a way of doing what you want that doesn't involve Depth API. Have you tried this? https://developer.oculus.com/documentation/unity/unity-customize-passthrough-passthrough-occlusions/

**Comment by TudorJude** [comment]
Hope my suggested solution helps. As this issue isn't directly related to the project, I'm closing it.
