### ISSUE TITLE
Extension possibilities

### ISSUE THREAD

**Issue by ntlin107AC1012** [oculus-samples/Unity-DepthAPI#15]
Is it possible to track a real right hand image and mirror a left hand using this api?

**Comment by vasylbo** [comment]
Hi,
The depth information doesn't hold any segmentation information in it, meaning that we don't know where the hands are based on the depth.
This sounds like something that will require our hand tracking feature to be enabled. 
Please, checkout how to set it up here - https://developer.oculus.com/documentation/unity/unity-handtracking/
