### ISSUE TITLE
Check if depth sensor is available

### ISSUE THREAD

**Issue by MollerAndre** [oculus-samples/Unity-DepthAPI#18]
Is there a way to check if Depth Sensor is available on the Quest model an user is using?
If I enable environment depth occlusion on a Quest 3 device everything is fine, but if I do it on a Quest 2 device which does not have depth sensor materials using depth-occlusion shaders are not show at all. I need a reliable way to check (even for future Quest models) if I can enable or not depth occlusion on my scene.

**Comment by TudorJude** [comment]
Hey MollerAndre,

Yes, there is a way to check that. If you go to the EnvironmentDepthTextureProvider.cs script, you'll see that in the Start function, we use such functionality.

```C#
            if (!Utils.GetEnvironmentDepthSupported())
            {
                _isDepthTextureAvailable = false;
                enabled = false;
                return;
            }
```

This fix just landed very recently, so you will have to update the depth API package.

Cheers

**Comment by TudorJude** [comment]
Closing issue.
