### ISSUE TITLE
Debugging in Unity Editor

### ISSUE THREAD

**Issue by Strubu** [oculus-samples/Unity-DepthAPI#2]
Works perfect when build and run on the Quest 3. 

Is there any way to make it work in the Unity editor to debug my applications? 
I have Passthrough over Oculus Link and Share Point Cloud over Oculus Link activated, but the right eye projection seems off and all objects with occlusion shader disappear, regardless of if they are occluded or not.

**Comment by vasylbo** [comment]
Hi
Depth over link is currently unsupported. It's in active development, and this repository will fully support it when available.

**Comment by Strubu** [comment]
Thanks for the quick answer.
