### ISSUE TITLE
Missing prefabs

### ISSUE THREAD

**Issue by brentjohnston** [oculus-samples/Unity-DepthAPI#22]
The git clone was successful but when I open the scenes I have missing prefabs and these errors. I am using Unity 2022.3.17f1, the newest meta xr all in one sdk, and https://github.com/oculus-samples/Unity-StarterSamples which all of those demo scenes work. I tried passthrough example in the editor and it works also, I wanted to import this depth api to try it out but has errors and a missing Sceneswitcher prefab: 
![error](https://github.com/oculus-samples/Unity-DepthAPI/assets/23625562/2e22a114-c7af-4ea3-93b2-a63172e8b321)

**Comment by TudorJude** [comment]
The prefab is there, something seems to have gone wrong when you cloned it. Could you try closing, deleting Library folder and reopening. If that doesn't work, try recloning.

**Comment by brentjohnston** [comment]
![git](https://github.com/oculus-samples/Unity-DepthAPI/assets/23625562/d8e5fce1-3075-43c9-a903-563bfb731fe6)

Yes I tried deleting it same missing prefab and errors.

**Comment by brentjohnston** [comment]
I deleted library folder and depth api again, recloned with lfs when it starts the loading on the unity splashscreen screen I get this whenenever depth api is cloned and present. It doesn't do the error if I delete it.
![startuperror](https://github.com/oculus-samples/Unity-DepthAPI/assets/23625562/10110f76-fc04-4f24-8ce6-e313694eb75a)

**Comment by brentjohnston** [comment]
That was just the default passthrough scene from Meta sample I had open, when I open the depth api sample project and it's the same errors. I was just showing the errors at bottom when the folder is present.

**Comment by brentjohnston** [comment]
Sorry I was confused also, I had the occlusion one open when taking screenshot, is this the right one? All of the sample scenes I do in the depth api samples do this. 
![Uploading errors.jpg…]()

**Comment by brentjohnston** [comment]
I just double clicked the hands removal scene and this shows up, is this not familiar? I'm not sure what I am looking at either. Is it possible the Oculus Start Samples is conflicting? https://github.com/oculus-samples/Unity-StarterSamples

![scene](https://github.com/oculus-samples/Unity-DepthAPI/assets/23625562/7af02b69-abe0-451e-a012-cc9fd0c891e2)

**Comment by brentjohnston** [comment]
Ahh, I don't know why I had assumed to git clone it to my project assets folder. Didn't realize it was an entire unity project. My fault, thanks for your help.
