### ISSUE TITLE
No Occlusion show on built file

### ISSUE THREAD

**Issue by tranquanglam123** [oculus-samples/Unity-DepthAPI#28]
I have cloned the project to my PC. Then open it in 2 separate Unity project, one for URP and one for BIRP.
The problem is, when I built into APK, 
-In TogglerOcclusion scene, when I press A button to change the occlusion type, all the grab object disappear.
-In the other scene, I can only see No Occlusion objects.

All the settings are remained as newly cloned.

**Comment by TudorJude** [comment]
Hey tranquanglam123,

Looks like you might be missing some setting, the PST should handle all of that. Bottom right corner, you should have a little oculus icon that will communicate any issue to you. What device are you using? Depth API is only supported on the Quest 3.

**Comment by tranquanglam123** [comment]
> Hey tranquanglam123,
> 
> Looks like you might be missing some setting, the PST should handle all of that. Bottom right corner, you should have a little oculus icon that will communicate any issue to you. What device are you using? Depth API is only supported on the Quest 3.

Thanks for your support, I actually found the reason yesterday after posting it.  It was about turning on the experimental features on the Quest 3
I did miss some settings, in order to make it work , I have to turn on the experimental by using the Powershell, navigating to the SDK folder, access the adb.exe with the following code
./adb.exe shell setprop debig.Oculus.experimentalEnabled 1
