### ISSUE TITLE
Didnt work with SDKv62?

### ISSUE THREAD

**Issue by Spphire** [oculus-samples/Unity-DepthAPI#29]
I have 2 projects with SDKv60 and v62.
Depthapi works well in SDKv60 but not in v62.
The model remains transparent all the time.
I dont know why but the version of SDK seems the only difference between them

**Comment by TudorJude** [comment]
Hey Spphire,

Sorry for the delayed response, could you please tell me the version of Unity you are running?

Thanks

**Comment by Spphire** [comment]
> Hey Spphire,
> 
> Sorry for the delayed response, could you please tell me the version of Unity you are running?
> 
> Thanks

2022.3.15

**Comment by TudorJude** [comment]
I'm trying to reproduce it, in the meantime, could you please delete your Library folder and try to build again?

**Comment by TudorJude** [comment]
Can you supply any logs? Try removing your app from the device before reinstalling it to clear all caches. I've been trying to reproduce it, but have had no luck so far.

**Comment by Spphire** [comment]
> Can you supply any logs? Try removing your app from the device before reinstalling it to clear all caches. I've been trying to reproduce it, but have had no luck so far.

Logs for what, I'm new to Android platform development ><

**Comment by TudorJude** [comment]
There's a tool that comes pre-installed with Unity, called adb. You need to add this to your Environment Variables so that you can use it in command line. Then you can type in the "logcat" command. This command 'adb logcat > out.txt' will put out the logs from your device into an out.txt file. Alternatively, Unity has this package but I am unfamiliar with it. https://docs.unity3d.com/Packages/com.unity.mobile.android-logcat@0.1/manual/index.html

**Comment by Spphire** [comment]
> There's a tool that comes pre-installed with Unity, called adb. You need to add this to your Environment Variables so that you can use it in command line. Then you can type in the "logcat" command. This command 'adb logcat > out.txt' will put out the logs from your device into an out.txt file. Alternatively, Unity has this package but I am unfamiliar with it. https://docs.unity3d.com/Packages/com.unity.mobile.android-logcat@0.1/manual/index.html

![image](https://github.com/oculus-samples/Unity-DepthAPI/assets/56157591/6be7af5d-dcfb-45f0-8614-12befff335e4)
I got it! v60sdk will ask to enable experimental features when building the project but not v62sdk, even I enable the experimental features
![image](https://github.com/oculus-samples/Unity-DepthAPI/assets/56157591/e87b4a15-55a6-40ee-8783-a4e4af00cd53)

**Comment by TudorJude** [comment]
That shouldn't be it, Depth API is now out of experimental. Something else is wrong with your project. If you could send some logs, I could see get a better idea as to what's happening in your project.

**Comment by TudorJude** [comment]
Wait, I just noticed one of the logs you posted here.  Can you please check if you have the scene permission enabled for your app? That's something you have to do yourself app-side. To check if your app has scene permission enabled, go to your quest's settings area, under permissions, and check if spatial data is enabled for your Depth API enabled app. 

To ebable scene permission, you can write code to do that, or set the "Scene" tickbox on your OVR camera:
![image](https://github.com/oculus-samples/Unity-DepthAPI/assets/16278394/2af994dd-15b7-408a-bd1d-d790f1b270a6)

**Comment by Spphire** [comment]
> Wait, I just noticed one of the logs you posted here. Can you please check if you have the scene permission enabled for your app? That's something you have to do yourself app-side. To check if your app has scene permission enabled, go to your quest's settings area, under permissions, and check if spatial data is enabled for your Depth API enabled app.
> 
> To ebable scene permission, you can write code to do that, or set the "Scene" tickbox on your OVR camera: ![image](https://private-user-images.githubusercontent.com/16278394/313605109-2af994dd-15b7-408a-bd1d-d790f1b270a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NjEwNjcsIm5iZiI6MTcxMDc2MDc2NywicGF0aCI6Ii8xNjI3ODM5NC8zMTM2MDUxMDktMmFmOTk0ZGQtMTViNy00MDhhLWJkMWQtZDc5MGYxYjI3MGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDExMTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZTVjM2ZjOGFlZmI2OTMwOGU4N2ZlNGYwOTQ0NGVjMTNkMjEzOGM1Yjc2M2NmZGZmOGQ2NDU4ODYwN2MyNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EgkW-n_cTenu47Bajy2p14dksYIho0lVPc7Nqxvb7hk)

That's the point! Thank you so much!
