### ISSUE TITLE
Using Shader Graph

### ISSUE THREAD

**Issue by qlee01** [oculus-samples/Unity-DepthAPI#3]
Hey, is there a way to use shader graph for this? Is it possible to wire the given vertex / fragment pieces to the corresponding stages in shader graph?

**Comment by vasylbo** [comment]
It should be possible, but we didn't try yet. 
It's already in our backlog to add shadergraph support in the urp package.

**Comment by qlee01** [comment]
> It should be possible, but we didn't try yet. It's already in our backlog to add shadergraph support in the urp package.

thanks! I will try a bit, have a rough idea how to do it, just wanted to ask because this could have saved a few hours of work, especially as testing seems only be possible on build / device right now.

**Comment by velickolb** [comment]
> > It should be possible, but we didn't try yet. It's already in our backlog to add shadergraph support in the urp package.
> 
> thanks! I will try a bit, have a rough idea how to do it, just wanted to ask because this could have saved a few hours of work, especially as testing seems only be possible on build / device right now.

Hey I gave it a try but didn't went far with it. Could you give me some directions on how would I do it in Shader Graph?

**Comment by qlee01** [comment]
> > > It should be possible, but we didn't try yet. It's already in our backlog to add shadergraph support in the urp package.
> > 
> > 
> > thanks! I will try a bit, have a rough idea how to do it, just wanted to ask because this could have saved a few hours of work, especially as testing seems only be possible on build / device right now.
> 
> Hey I gave it a try but didn't went far with it. Could you give me some directions on how would I do it in Shader Graph?

I also did not succeed yet. Still have some mixup of position data, not clear where to use object, works, screen space. I can see some effect, but it seems to be mirrored and not stable in space. In principal you need two custom functions I guess, one connected to position node in vertex stage, and one to alpha or alpha threshold in fragment stage, using alpha clipping. You can use custom interpolater to send data from vertex to fragment stage.

**Comment by BigStoagie** [comment]
> > > > It should be possible, but we didn't try yet. It's already in our backlog to add shadergraph support in the urp package.
> > > 
> > > 
> > > thanks! I will try a bit, have a rough idea how to do it, just wanted to ask because this could have saved a few hours of work, especially as testing seems only be possible on build / device right now.
> > 
> > 
> > Hey I gave it a try but didn't went far with it. Could you give me some directions on how would I do it in Shader Graph?
> 
> I also did not succeed yet. Still have some mixup of position data, not clear where to use object, world or screen space. I can see some effect, but it seems to be mirrored and not stable in space. In principal you need two custom functions I guess, one connected to position node in vertex stage, and one to alpha or alpha threshold in fragment stage, using alpha clipping. You can use custom interpolater to send data from vertex to fragment stage.

So I've been messing around with trying to get this working in shadergraph and I seem to be having trouble with utilizing the function that calculates the occlusion value. If I use a custom node to write a function that calls the function meta provides it gives me an error saying something about a redefinition of _Time at line 40. I was just wondering if you could provide any guidance if you've gotten that function to work.

**Comment by vasylbo** [comment]
We haven't started investigating it yet.
The redefinition of _Time sounds like there is a conflict of includes in shader graph files and the code in the custom node. It's possible that to implement it, we'll require to refactor the hlsl files that we provide. I'll update here when we have more info on this.

**Comment by Ricimon** [comment]
I managed to somewhat get a shader graph implementation working, but for some reason the occlusion doesn't work if the occluding object is too far from the camera.

This is the Occlusion subgraph that outputs an occlusionValue. It's got 2 custom functions, one to get positionCS and positionNDC, and one to get the occlusionValue.

![image](https://github.com/oculus-samples/Unity-DepthAPI/assets/24966782/3c8747ae-6e19-4255-9dfc-9256aa5eae2c)
![image](https://github.com/oculus-samples/Unity-DepthAPI/assets/24966782/7701b0ce-44a6-497f-a355-76496c680afb)

**Occlusion.hlsl**
```
#ifndef OCCLUSION_INCLUDED
#define OCCLUSION_INCLUDED

#ifndef SHADERGRAPH_PREVIEW
	#include "Packages/com.meta.xr.depthapi.urp/Shaders/EnvironmentOcclusionURP.hlsl"
#endif

#pragma multi_compile _ HARD_OCCLUSION SOFT_OCCLUSION

void CalculateEnvironmentDepthOcclusion_float (float2 uv, float sceneDepth, out float occlusionValue){
	#ifndef SHADERGRAPH_PREVIEW
		occlusionValue = CalculateEnvironmentDepthOcclusion(uv, sceneDepth);
	#else
		occlusionValue = 1;
	#endif
}

void CalculateEnvironmentDepthOcclusion_half (half2 uv, half sceneDepth, out half occlusionValue){
	#ifndef SHADERGRAPH_PREVIEW
		occlusionValue = CalculateEnvironmentDepthOcclusion(uv, sceneDepth);
	#else
		occlusionValue = 1;
	#endif
}

#endif // OCCLUSION_INCLUDED
```

The subgraph is then added to a shader graph like so

![image](https://github.com/oculus-samples/Unity-DepthAPI/assets/24966782/2cd5f723-3b3e-42e1-b2e0-3fc7033fbc4a)

**Comment by Ricimon** [comment]
I managed to somewhat get a shader graph implementation working, but for some reason the occlusion doesn't work if the occluding object is too far from the camera.

This is the Occlusion subgraph that outputs an occlusionValue. It's got 2 custom functions, one to get positionCS and positionNDC, and one to get the occlusionValue.

<img src="https://github.com/oculus-samples/Unity-DepthAPI/assets/24966782/3c8747ae-6e19-4255-9dfc-9256aa5eae2c" width=800 /> \
<img src="https://github.com/oculus-samples/Unity-DepthAPI/assets/24966782/426b8431-ea8b-49e4-a644-180158448425" width=400 />
<img src="https://github.com/oculus-samples/Unity-DepthAPI/assets/24966782/7701b0ce-44a6-497f-a355-76496c680afb" width=400 />

**Occlusion.hlsl**
```
#ifndef OCCLUSION_INCLUDED
#define OCCLUSION_INCLUDED

#ifndef SHADERGRAPH_PREVIEW
	#include "Packages/com.meta.xr.depthapi.urp/Shaders/EnvironmentOcclusionURP.hlsl"
#endif

#pragma multi_compile _ HARD_OCCLUSION SOFT_OCCLUSION

void CalculateEnvironmentDepthOcclusion_float (float2 uv, float sceneDepth, out float occlusionValue){
	#ifndef SHADERGRAPH_PREVIEW
		occlusionValue = CalculateEnvironmentDepthOcclusion(uv, sceneDepth);
	#else
		occlusionValue = 1;
	#endif
}

void CalculateEnvironmentDepthOcclusion_half (half2 uv, half sceneDepth, out half occlusionValue){
	#ifndef SHADERGRAPH_PREVIEW
		occlusionValue = CalculateEnvironmentDepthOcclusion(uv, sceneDepth);
	#else
		occlusionValue = 1;
	#endif
}

#endif // OCCLUSION_INCLUDED
```

The subgraph is then added to a shader graph like so

![image](https://github.com/oculus-samples/Unity-DepthAPI/assets/24966782/2cd5f723-3b3e-42e1-b2e0-3fc7033fbc4a)

This works when the occluding object is close to the camera, but for some reason not when it's a little far. The white box on the left is the included code URP Unlit, while the gray box on the right is the shader graph.
<img src="https://github.com/oculus-samples/Unity-DepthAPI/assets/24966782/c0cb2c93-e668-4291-a03f-a921c11035fa" width=300 /> <img src="https://github.com/oculus-samples/Unity-DepthAPI/assets/24966782/67de9e26-e1d1-40b9-bd6e-c596c45ac336" width=300 />

Any ideas on what's wrong here?

**Comment by velickolb** [comment]
> I managed to somewhat get a shader graph implementation working, but for some reason the occlusion doesn't work if the occluding object is too far from the camera.
> 
> This is the Occlusion subgraph that outputs an occlusionValue. It's got 2 custom functions, one to get positionCS and positionNDC, and one to get the occlusionValue.
> 
> <img alt="" width="800" src="https://user-images.githubusercontent.com/24966782/278784234-3c8747ae-6e19-4255-9dfc-9256aa5eae2c.png"> <img alt="" width="400" src="https://user-images.githubusercontent.com/24966782/278784369-426b8431-ea8b-49e4-a644-180158448425.png"> <img alt="" width="400" src="https://user-images.githubusercontent.com/24966782/278724483-7701b0ce-44a6-497f-a355-76496c680afb.png">
> 
> **Occlusion.hlsl**
> 
> ```
> #ifndef OCCLUSION_INCLUDED
> #define OCCLUSION_INCLUDED
> 
> #ifndef SHADERGRAPH_PREVIEW
> 	#include "Packages/com.meta.xr.depthapi.urp/Shaders/EnvironmentOcclusionURP.hlsl"
> #endif
> 
> #pragma multi_compile _ HARD_OCCLUSION SOFT_OCCLUSION
> 
> void CalculateEnvironmentDepthOcclusion_float (float2 uv, float sceneDepth, out float occlusionValue){
> 	#ifndef SHADERGRAPH_PREVIEW
> 		occlusionValue = CalculateEnvironmentDepthOcclusion(uv, sceneDepth);
> 	#else
> 		occlusionValue = 1;
> 	#endif
> }
> 
> void CalculateEnvironmentDepthOcclusion_half (half2 uv, half sceneDepth, out half occlusionValue){
> 	#ifndef SHADERGRAPH_PREVIEW
> 		occlusionValue = CalculateEnvironmentDepthOcclusion(uv, sceneDepth);
> 	#else
> 		occlusionValue = 1;
> 	#endif
> }
> 
> #endif // OCCLUSION_INCLUDED
> ```
> 
> The subgraph is then added to a shader graph like so
> 
> ![image](https://user-images.githubusercontent.com/24966782/278784309-2cd5f723-3b3e-42e1-b2e0-3fc7033fbc4a.png)
> 
> This works when the occluding object is close to the camera, but for some reason not when it's a little far. The white box on the left is the included code URP Unlit, while the gray box on the right is the shader graph. <img alt="" width="300" src="https://user-images.githubusercontent.com/24966782/278784894-c0cb2c93-e668-4291-a03f-a921c11035fa.jpg"> <img alt="" width="300" src="https://user-images.githubusercontent.com/24966782/278784896-67de9e26-e1d1-40b9-bd6e-c596c45ac336.jpg">
> 
> Any ideas on what's wrong here?

I tried playing with the values in the _EnvironmentDepthTextureProvider.cs_. Setting the custom _depthFarZ_ and _depthFarZ_  values seems to have an affect but not the expected one.

**Comment by NicolasAbo17** [comment]
I tried this and the object just dissapear for me, I am multiplying the occlussion to my original ambient color. It would be good to have meta feedback on this shader graph, just to see how to get it working.

![image](https://github.com/oculus-samples/Unity-DepthAPI/assets/38436508/a16ada65-f1b8-47b8-8cc8-a356ea55c825)

**Comment by TudorJude** [comment]
Hello everyone,

Sorry for the late reply on this issue. There will be a subgraph that handles occlusions with examples in the next update. For those of you that can't wait until then here's how you can implement it yourselves:

### 1. Create an occlusion subgraph like so:
![image](https://github.com/oculus-samples/Unity-DepthAPI/assets/16278394/b471aee0-c443-4b29-b71a-946c310dc731)

The CalculateEnvironmentDepthOcclusion node is a custom function node that has this hlsl code in it:
```
#pragma multi_compile _ HARD_OCCLUSION SOFT_OCCLUSION

#ifndef SHADERGRAPH_PREVIEW
#include "Packages/com.meta.xr.depthapi/Runtime/URP/EnvironmentOcclusionURP.hlsl"
#endif

void CalculateEnvironmentDepthOcclusion_float(float3 posWorld, out float occlusionValue)
{
#ifndef SHADERGRAPH_PREVIEW
    occlusionValue = META_DEPTH_GET_OCCLUSION_VALUE_WORLDPOS(posWorld, 0.0);
#else
    occlusionValue = 1;
#endif
}

void CalculateEnvironmentDepthOcclusion_half(float3 posWorld, out half occlusionValue)
{
#ifndef SHADERGRAPH_PREVIEW
    occlusionValue = META_DEPTH_GET_OCCLUSION_VALUE_WORLDPOS(posWorld, 0.0);
#else
    occlusionValue = 1;
#endif
}
```

Graph inspector looks like this for it:
![image](https://github.com/oculus-samples/Unity-DepthAPI/assets/16278394/2c549dd4-6dc5-4bb5-8fea-f9eb69967b31)

### 2. Add it to your Shadergraph. Here's an example:
![image](https://github.com/oculus-samples/Unity-DepthAPI/assets/16278394/e30b72de-0c97-400c-b788-2690eebf5803)

In this instance I enable alpha clipping and set its threshold to 0. 0 alpha pixels will be occluded.

**Comment by Spphire** [comment]
> Hello everyone,
> 
> Sorry for the late reply on this issue. There will be a subgraph that handles occlusions with examples in the next update. For those of you that can't wait until then here's how you can implement it yourselves:
> 
> ### 1. Create an occlusion subgraph like so:
> ![image](https://private-user-images.githubusercontent.com/16278394/286881471-b471aee0-c443-4b29-b71a-946c310dc731.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjQzNjgsIm5iZiI6MTcwMjg2NDA2OCwicGF0aCI6Ii8xNjI3ODM5NC8yODY4ODE0NzEtYjQ3MWFlZTAtYzQ0My00YjI5LWI3MWEtOTQ2YzMxMGRjNzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDAxNDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MDJmM2QzZWRkMWEzYTcwNTgyNWI0MWEwZTI2ZmE1MWJkNWI3N2JiMmY3ODM1ZWQzZTMwYjBkNmM4NDVkMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SPsSUgqVqcXRNxDmFNGwJs_-D3VWFF_OVfWm6ZkW028)
> 
> The CalculateEnvironmentDepthOcclusion node is a custom function node that has this hlsl code in it:
> 
> ```
> #pragma multi_compile _ HARD_OCCLUSION SOFT_OCCLUSION
> 
> #ifndef SHADERGRAPH_PREVIEW
> #include "Packages/com.meta.xr.depthapi/Runtime/URP/EnvironmentOcclusionURP.hlsl"
> #endif
> 
> void CalculateEnvironmentDepthOcclusion_float(float3 posWorld, out float occlusionValue)
> {
> #ifndef SHADERGRAPH_PREVIEW
>     occlusionValue = META_DEPTH_GET_OCCLUSION_VALUE_WORLDPOS(posWorld, 0.0);
> #else
>     occlusionValue = 1;
> #endif
> }
> 
> void CalculateEnvironmentDepthOcclusion_half(float3 posWorld, out half occlusionValue)
> {
> #ifndef SHADERGRAPH_PREVIEW
>     occlusionValue = META_DEPTH_GET_OCCLUSION_VALUE_WORLDPOS(posWorld, 0.0);
> #else
>     occlusionValue = 1;
> #endif
> }
> ```
> 
> Graph inspector looks like this for it: ![image](https://private-user-images.githubusercontent.com/16278394/286882548-2c549dd4-6dc5-4bb5-8fea-f9eb69967b31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjQzNjgsIm5iZiI6MTcwMjg2NDA2OCwicGF0aCI6Ii8xNjI3ODM5NC8yODY4ODI1NDgtMmM1NDlkZDQtNmRjNS00YmI1LThmZWEtZjllYjY5OTY3YjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDAxNDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhOGMxN2QwYjFhYjRlMTc0OWQ2ZjJiNzFjOGYzOGJmZjdiZTIxNDllYWZhZDhkMjdkNjhiNGM0NmYyMDdiODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0i1gtzoQrrJ-0VARfw7xb0Lrsfv01NU7PLdEEB0KPRg)
> 
> ### 2. Add it to your Shadergraph. Here's an example:
> ![image](https://private-user-images.githubusercontent.com/16278394/286883089-e30b72de-0c97-400c-b788-2690eebf5803.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjQzNjgsIm5iZiI6MTcwMjg2NDA2OCwicGF0aCI6Ii8xNjI3ODM5NC8yODY4ODMwODktZTMwYjcyZGUtMGM5Ny00MDBjLWI3ODgtMjY5MGVlYmY1ODAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDAxNDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlYzJlN2M4N2QxYzM0N2I5YmQ4MjZmYjUxNGVmYTMyZjlkYjBlODhhZGE4NmIyNWUzZmZhMzBiZDJiOGE5OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aKUQNXJDzgULPK-huCqAhEJzv29Zh8Fh7WOamWVprBY)
> 
> In this instance I enable alpha clipping and set its threshold to 0. 0 alpha pixels will be occluded.

Can it now be tested on Oculus-Link? and what's the mean of the second param(0.0) of function:
```hlsl
occlusionValue = META_DEPTH_GET_OCCLUSION_VALUE_WORLDPOS(posWorld, 0.0);
```

**Comment by TudorJude** [comment]
Hey Spphire,

* We will release an update very soon that will have Link support.
* The second parameter is the environment depth bias, you can expose that in your subgraph as well if you wish. Environment depth bias is explained in the readme and there's a sample scene called "SceneAPIPlacement" that showcases its usage.

**Comment by Spphire** [comment]
> Hey Spphire,
> 
> * We will release an update very soon that will have Link support.
> * The second parameter is the environment depth bias, you can expose that in your subgraph as well if you wish. Environment depth bias is explained in the readme and there's a sample scene called "SceneAPIPlacement" that showcases its usage.

Thanks for reply!

I tried it today, I wondered if quest2 can use it？

I tried it both with oculus-link and building and installing into quest2, 

oculus-link: the cube with shadergraph seems normal in unity-editor, but when it start running, the cube become totally transparent

install in quest2: the cube is totally transparent after running

so maybe quest2 cant use it?

**Comment by TudorJude** [comment]
Depth API is only supported on Quest 3.

**Comment by TudorJude** [comment]
Closing issue, the solution is now up on this repo.
