### ISSUE TITLE
normal based depth occlusion

### ISSUE THREAD

**Issue by alfiolocastro** [oculus-samples/Unity-DepthAPI#35]
I would like to achieve a normal based depth occlusion so that you can, for instance, render something behind a wall or roof that would be elsewhere occluded, any advice?

**Comment by TudorJude** [comment]
Could you please go into more detail? I'm having a bit of trouble visualizing what you mean.

**Comment by alfiolocastro** [comment]
Sure!
I'll make a simple example: imagine I'll want to open a hole in the ground only and the material shader is a depth api custom shader. Right now the hole in the ground and every mesh (sharing the same shader) under the ground level would be occluded.
Passing a normal parameter we could say to the depth api to ignore occlusion in a direction.

**Comment by TudorJude** [comment]
Hey, so this problem is rather non-trivial and we have it on our todo list. Once we have something, I'll update this thread.
