### ISSUE TITLE
Conflicts with the official Oculus Integration package

### ISSUE THREAD

**Issue by BlueJayVRStudio** [oculus-samples/Unity-DepthAPI#4]
Hello, will the DepthAPI get integrated into the official Oculus Integration kit in the near future? It seems like trying to merge this with preexisting projects often results in plugin or code conflicts. Otherwise, the occlusion shader from this API works fantastically and this will most likely be quintessential in future mixed reality applications. As it currently stands, mixed reality mode doesn't play nicely with large dynamic or static objects as they will impede vision of surrounding physical objects or people; these are both a safety and an aesthetic concerns, which is probably why this is one of the more prioritized features in Apple's vision pro.

**Comment by vasylbo** [comment]
We have an issue that the package requires UPM version of Integration SDK, and that blocks the possibility of using all-in-one integration package. We'll resolve that tomorrow, if this was the issue on your side.

For the integration package: we are still perfecting this API and this github repository is a great place to gather feedback from developers and understand how we can improve it. The ambition to incorporate lower level stuff into integration SDK so developers can start implementing occlusions just having our Integration SDK is there and, we are actively working on it. But that will require a bit more time so in the meantime I would be interested in unblocking you with this package.

**Comment by BlueJayVRStudio** [comment]
Understood, thank you!

Is this the UPM package you're referring to? https://openupm.com/packages/com.oculus.unity-integration/ and when you say unblocking, does that refer to some kind of UPM credentials?

**Comment by vasylbo** [comment]
This one - https://npm.developer.oculus.com/-/web/detail/com.meta.xr.sdk.utilities. You can read about it here: https://developer.oculus.com/documentation/unity/unity-package-manager/
For unblocking I meant that I'm interested in helping you resolve your issue with this repository. We should publish a fix that will remove dependency to the UPM package, so you can use DepthAPI package with all-in-one integration package.
