### ISSUE TITLE
Updating to v61 breaks Unity 

### ISSUE THREAD

**Issue by Mrbside** [oculus-samples/Unity-DepthAPI#42]
Unity 2022.3.7f1 
Meta XR SDK v65
Windows 11

So I had my project with both Depth API packages on v60, today I had the great idea to click on the update button in the first Depth API package, to download v61, when it was done, the editor frooze, I could click on it on the task bar to minimize it but nothing else, also editor didn't go in "not responding state", I closed the editor and when the editor is loading it stops and show "unity no valid user created or default window layout found...." with button options for Quit or reset factory setitngs.

Clicking on the reset option does nothing and the message box reappears immediately, I found on a forum the suggestion to delete the file Library/ArtifactDB, this worked and after some loading time, the editor opened again just with layout reseted.

**Comment by TudorJude** [comment]
Hey Mrbside,

Sorry you're having difficulties. Have you read the Troubleshooting in the github readme? It addresses this exact issue. Unfortunately, there isn't much that we can do here, it's related to a unity package that is a dependency.
