### ISSUE TITLE
Feature Request: Hand Removal w/Virtual Gloves & Controllers

### ISSUE THREAD

**Issue by vtimejc** [oculus-samples/Unity-DepthAPI#44]
If I understand correctly, hand removal removes the hands from the depth based occlusion and then uses a mask from the hand tracking.

In a game where the player is wearing gloves, it would by nice to have the option to remove hands (including when using controllers) to avoid the occlusion messing with gloves and/or weapons etc.

**Comment by TudorJude** [comment]
Hey,

This isn't something in our plans in the near future.
