### ISSUE TITLE
Environment Depth Occlusion shifts the occlusion when the MRUK room is rotated

### ISSUE THREAD

**Issue by Boysle** [oculus-samples/Unity-DepthAPI#45]
So I am using the scanned room with MRUK. For specific purposes, I have to rotate the room so that the desk aligns with the default coordinate system in unity. 
However, doing this causes my depth occlusion to act weirdly, creating occlusions in shifted locations. The image below happens when the room is rotated by 10 degrees on the Y-axis.

![Ekran görüntüsü 2024-06-25 171931](https://github.com/oculus-samples/Unity-DepthAPI/assets/53544274/2ce8e49f-cd24-48c6-8ce5-52e154f3807d)

Does anybody know how to solve this problem?
So far I tried adjusting the Custom Tracking Space Transform in the Environment Depth Texture Provider script but it does not seem to work.

**Comment by TudorJude** [comment]
Hey Boysle,

What exactly are you rotating? What did you set in the custom tracking space transform field?

**Comment by Boysle** [comment]
I am rotating the following transform: **MRUK.Instance.GetCurrentRoom().transform**

Which can be seen in Unity as ![image](https://github.com/oculus-samples/Unity-DepthAPI/assets/53544274/b39af6c4-c072-4184-b681-401352086463)

For the Custom Tracking Space Transform field, I tried setting a dummy camera object that follows the camera with a negative rotation to cancel out the effect caused by the world's rotation but it did not work out.

**Comment by TudorJude** [comment]
Hey,

I just tried to reproduce this on our side, but couldn't. Internally, we have changed the codebase quite a bit, though, so perhaps it was something we missed that got remedied. The update is due to launch sometime around the 9th of July. Until then, could you please tell me if this is happening over device or over Link?

Thanks

**Comment by Boysle** [comment]
Sorry for the late response @TudorJude,

You were correct about the Quest Link. I have been working over Link and it seems that was the problem.
Building and running the .apk file on Quest 3 with the default options of the EnvironmentDepthOcclusion works perfectly.

Thanks for the help!

**Comment by TudorJude** [comment]
Hello,

It seems that there are some known issues with Link, we have some QA reporting something similar to this and we're actively looking into it. For now, I'll add this to our known issues section, thanks for reporting it and sorry for the inconvenience.
