### ISSUE TITLE
DepthAPI and MetaXR simulator

### ISSUE THREAD

**Issue by alfiolocastro** [oculus-samples/Unity-DepthAPI#46]
Hi there,
I'm trying to use MetaXR simulator to test DepthAPI behaviours on my shaders. From simulator v65 up it is said on release notes that should be possible to emulate DepthAPI with no changes in code but looks like it doesn't. For instance Utils.GetEnvironmentDepthSupported() does return false on the meta xr simulator and this deactivates EnvironmentDepthTextureProvider.cs component that does not populate the depth texture for the shaders.
Am I missing something?

A.

**Comment by alfiolocastro** [comment]
UPDATE
I tested the simulator(v66.0.1) on the plain DepthAPI sample with no success, there's no occlusion.

**Comment by TudorJude** [comment]
Hello,

Sorry for the delay, but I reached out to the XRSim team. It seems that starting v66, a bug was introduced, so it will not work. The fix should be arriving in a future update.

**Comment by alfiolocastro** [comment]
Hi!
I was wondering if there'a a way to reach the XRSim team. Still no occlusion with XRSim (68.0.0) and Depth API (68.0.0)
