### ISSUE TITLE
Dependency on com.meta.xr.sdk.utilities generate conflict with original oculus integration

### ISSUE THREAD

**Issue by NicolasAbo17** [oculus-samples/Unity-DepthAPI#5]
If you already have oculus integration and add this package it generates a conflict with a duplicate dll, and if you delete the windows dll it will generate an error which you have to always restart the project every time you open it. 
![image](https://github.com/oculus-samples/Unity-DepthAPI/assets/38436508/0022ba30-43f1-48a2-ad0f-124bf80edf68)
If you delete the android plugin which is also duplicate, the project works fine, so for android is ok

**Comment by vasylbo** [comment]
Thanks for reporting. We'll remove the dependency on meta.xr.sdk.utilities to fix this.

**Comment by TudorJude** [comment]
This issue should be solved now.
