### ISSUE TITLE
Impossible to add the "EnvironmentDepth.cs" component to a GameObject

### ISSUE THREAD

**Issue by MelonSpeedruns** [oculus-samples/Unity-DepthAPI#51]
As the title says, adding `EnvironmentDepth.cs` to any GameObject will result in the following error. I am using the latest update of Core (66.0.0) and the latest version of Depth API (67.0.0)

![image](https://github.com/user-attachments/assets/eb484d4a-f9b4-48ea-9f72-63952a9ddc21)

**Comment by TudorJude** [comment]
Hey,

Try v67 of core, the Depth API packages rely on that. Second, I am unfamiliar with the script `EnvironmentDepth.cs`. Did you mean `EnvironmentDepthTextureProvider.cs`?. The image you linked seems to be about another script.

**Comment by MelonSpeedruns** [comment]
I will try v67 of Core! And I can't seem to find a script named `EnvironmentDepthTextureProvider.cs`, even while looking in all packages, on the latest version of Depth API.

**Comment by MelonSpeedruns** [comment]
Ok, after updating the `Meta MR Utility Kit` package to the latest (67.0.0) it also updated Core to 67.0.0, fixing the issue!

Thank you so much!
