### ISSUE TITLE
Occlusion really bad v67

### ISSUE THREAD

**Issue by angecroft** [oculus-samples/Unity-DepthAPI#52]
Testing both the sample scenes from this repo for Depth API v67 with URP and with BiRP. As you can see in the video (v67 build), it is nothing compared to the v66 Images and Gif available in the documentation. Also tested v66 on Quest3 and it's really not the same preview than in v67

https://github.com/user-attachments/assets/a2a96fc6-4547-4271-a995-70aa15feb774

**Comment by TudorJude** [comment]
Hello,

I need some more info and some clarification on you issue first. 
* The video that you are sharing, is this from a v66 version of the sdk or v67? 
* What do you mean by v66 images/gifs, the docs have v67 images, not v66. 
* Could you please share the OS version that you are on? 
* What version of Unity are you on?

**Comment by angecroft** [comment]
Hello, Thank you for your time.

The video is from v67 build with Unity 2022.3.36f1, on MacOS 14.5 with a M1 Pro.
I assumed the images and Gifs in the doc were from v66 or older since the occlusion seems ok. Sorry for the confusion

**Comment by TudorJude** [comment]
What about the OS on the headset?

**Comment by angecroft** [comment]
Hi, I'm using a Quest 3 with v66

**Comment by TudorJude** [comment]
Starting with v67 OS, the underlying mechanism for occlusions has changed and the v67 sdk accounts for that. So the v67 sdks (and therefore this sample) is meant for OS v67 and upwards. You might want to upgrade your headset OS . If you wish to keep the OS at v66, you will need to jump on an earlier commit in this github project, to get the pre v67 shaders and samples.

**Comment by angecroft** [comment]
Ok but if it's a breaking change, it will also break on any player's headset that doesn't have the v67

**Comment by angecroft** [comment]
I've upgraded my Quest 3 to v67 and rebuild again the samples, but I've got the exact same result as in the video I previously posted. So v67 on the headset doesn't seem to fix anything
@TudorJude
