### ISSUE TITLE
Allow non-OVRCameraRig rigs to use EnvironmentDepthManager

### ISSUE THREAD

**Issue by trev3d** [oculus-samples/Unity-DepthAPI#53]
Previously you could provide a custom tracking space transform to the EnvironmentDepthTextureProvider if you weren't using an OVRCameraRig. Now, moved to the core sdk, EnvironmentDepthManager doesn't expose a tracking space transform field and looks for an OVRCameraRig. If it cannot find one it will not provide the depth texture, reprojection matrices, etc. 

I need to support multiple headsets & platforms and cannot use an OVRCameraRig. I'm instead using Unity's generic XROrigin. Would it be possible to expose this field again? Thank you!

**Comment by TudorJude** [comment]
Hello,

The code was heavily refactored and this not being part of the EnvironmentDepthManager is an oversight. It will be remedied in a future update.  If a solution is needed earlier, I can supply a temporary one until the update is rolled out.

**Comment by trev3d** [comment]
I'm able to make this change myself, I would just prefer not to have to modify the core sdk package forever. Thank you!
