### ISSUE TITLE
Depth texture similar to Scene Depth?

### ISSUE THREAD

**Issue by GTD-Carthage** [oculus-samples/Unity-DepthAPI#54]
Hello all! I am hoping to reference the environment depth texture directly via Depth API to achieve certain shaders (namely in Shader Graph) - is there a way to access this and not just the occlusion result? Unfortunately, I am not exactly overly HLSL code inclined, thus trying to read all the includes at the moment is not working well for me.

We are hoping to get something similar to the result of Scene Depth node to control certain effects.

**Comment by TudorJude** [comment]
Hello,

Try this:
* Create a subnode that looks like this:
![image](https://github.com/user-attachments/assets/3ba90889-3986-43c2-b167-0110e64bbd7a)
* The Custom Function node should accept an HLSL file and have these params:
![image](https://github.com/user-attachments/assets/2bfad3cd-7774-484a-ae87-0cb10f8287a9)

* Here's the HLSL code: 
```HLSL
#pragma warning (disable : 3568)
#pragma multi_compile _ HARD_OCCLUSION SOFT_OCCLUSION

#ifndef SHADERGRAPH_PREVIEW
#include "Packages/com.meta.xr.sdk.core/Shaders/EnvironmentDepth/URP/EnvironmentOcclusionURP.hlsl"
#endif

void GetEnvironmentSceneDepth_float(float3 posWorld, out float environmentDepth) {
#ifndef SHADERGRAPH_PREVIEW
  const float4 depthSpace = mul(_EnvironmentDepthReprojectionMatrices[unity_StereoEyeIndex], float4(posWorld, 1.0));
  const float2 uvCoords = (depthSpace.xy / depthSpace.w + 1.0f) * 0.5f;
  environmentDepth = SampleEnvironmentDepthLinear(uvCoords);
#else
  environmentDepth = 0;
#endif
}

void GetEnvironmentSceneDepth_half(float3 posWorld, out float environmentDepth) {
#ifndef SHADERGRAPH_PREVIEW
  const float4 depthSpace = mul(_EnvironmentDepthReprojectionMatrices[unity_StereoEyeIndex], float4(posWorld, 1.0));
  const float2 uvCoords = (depthSpace.xy / depthSpace.w + 1.0f) * 0.5f;
  environmentDepth = SampleEnvironmentDepthLinear(uvCoords);
#else
  environmentDepth = 0;
#endif
}
```

This will give you the linear depth value at a certain world position.

**Comment by GTD-Carthage** [comment]
Thank you! This works perfectly and is exactly what we want!
