### ISSUE TITLE
Soft Occlusion softness changed after v67 update

### ISSUE THREAD

**Issue by dan-asa** [oculus-samples/Unity-DepthAPI#55]
It seems that the v67 update changed how soft occlusion is rendered. 

Using the same scenes from samples without changes after the update the soft occlusion is barely different from hard occlusion, the edges are very blocky with just a small edge blur. Before the update the edges where a lot smoother.

It would be nice to be able to adjust the softness of the edge, even if the trade off for a smoother edge is performance.

Before:
![OldSoftOcclusion](https://github.com/user-attachments/assets/961641ed-20ae-46b8-9aea-3825429b44ee)
After:
![NewSoftOcclusion](https://github.com/user-attachments/assets/dd9db583-409f-482c-a4b1-1ef58f7d3995)

**Comment by TudorJude** [comment]
Hey,

What operating system is your headset on?

**Comment by dan-asa** [comment]
At the time I made the screenshots the Quest 3 OS was on v65 version, in the meantime I updated to v68, but nothing changed.

**Comment by TudorJude** [comment]
There was someone else who experience this and upgrading didn't initially fix the issue. They mentioned restarting the quest several times after updating.

**Comment by dan-asa** [comment]
After a headset restart and reinstall of the build it is working now. Thank you!
