### ISSUE TITLE
Can't add the package.

### ISSUE THREAD

**Issue by Cloud-OG** [oculus-samples/Unity-DepthAPI#56]
![image](https://github.com/user-attachments/assets/346ec65f-82a6-40df-b78e-86114bfd24fb)
I use the url to add the package of DepthAPI, but the editer can't make it. My render pipeline is build in.

**Comment by TudorJude** [comment]
Is that the whole error message?

**Comment by TudorJude** [comment]
Off the top of my head, try making sure that the path is correct. Sometimes trailing white spaces get through when you copy certain links.  Try copying by pressing this button from the docs:
![image](https://github.com/user-attachments/assets/5b040cac-99e0-4314-bc8e-e85905016e30)

If this still doesn't solve it, I will need some more information on that error.

**Comment by Cloud-OG** [comment]
Thanks,I know why it didn't work.My new computer haven't downloaded the git.😂
![image](https://github.com/user-attachments/assets/dcaffcee-9054-4866-857c-0a8292f1a75a)
