### ISSUE TITLE
A more convenient way to set up Depth bias for GameObjects

### ISSUE THREAD

**Issue by Squashi11** [oculus-samples/Unity-DepthAPI#57]
The **Occlusion Depth Bias** component is a great tool to solve z-fighting. But how should one use it in a bigger projects ? Adding it to every single _GameObject_ by hands seems tedious to me. _Does Affect Children_ is a nice addition but there could be more options, thanks.
![image](https://github.com/user-attachments/assets/67058b54-630a-4f21-a2c2-139080221075)

**Comment by TudorJude** [comment]
Hello,

The environment depth bias can be set on a per material basis by calling those materials' SetFloat function and adjusting the `_EnvironmentDepthBias` value. You could reference your materials, and call this function for each. You could also call the static class method `Shader.SetGlobalFloat` for the environment depth bias, and to my understanding, that should modify the _EnvironmentDepthBias float for every shader., but that would of course set the same value on all materials which might not yield the desired effect.

That being said, we value the input and will look into a solution to streamline this process.

Thanks

**Comment by Squashi11** [comment]
I recently tried my own way of applying depthbias to every mesh renderer in the scene , this comes with a drawback where unity cant batch these objects together. So I returned back to this Issue and tried using static class method Shader.SetGlobalFloat for the environment depth bias. It doesnt seem to work in my code even when I change it to "Environment Depth Bias".

![image](https://github.com/user-attachments/assets/61fc7280-3f26-43c8-9de7-ef96f486407b)
![image](https://github.com/user-attachments/assets/d39e0719-6407-4410-8794-8eddb71b3d35)

**Comment by TudorJude** [comment]
SetGlobalFloat should work fine on materials that have normal shaders but if you use shadergraph, I think the reference name of your floats might be different. I remember form the other post that you were using shadergraph, so it's probably that.
