### ISSUE TITLE
Detail infomation request for the usage of the raycast script

### ISSUE THREAD

**Issue by QiuHong-1202** [oculus-samples/Unity-DepthAPI#59]
Firstly, thank you so much for maintaining this repo.

I am a new developer of quest 3 and I have read issue #16 and #49. However, I still have no idea about how to make the raycast work in my own project (BiRP). Could you please give me a more detail guideline?

The following things are what I have done.
1. config the DepthAPI using the infomation in this repo (my SDK is v68).
![image](https://github.com/user-attachments/assets/ea65e881-fa3e-4909-a185-f2dc85869567)

2. create scripts named `EnvironmentDepthAccess.cs`, a compute shader named `Raycast.compute` and then copy paste the code by @TudorJude in #49 
3. create a script `DepthRaycast.cs` for testing

```c#
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DepthRaycast : MonoBehaviour
{
    [SerializeField] private EnvironmentDepthAccess DepthAccess;
    // Start is called before the first frame update
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {
        Vector2 coord = new Vector2(0.5f, 0.5f); 
        EnvironmentDepthAccess.DepthRaycastResult result = DepthAccess.RaycastViewSpaceBlocking(coord);
        Debug.Log($"Raycast result: {result.Position}, {result.Normal}");
    }
}
```

5. config an object in my passthrough scene

![image](https://github.com/user-attachments/assets/9582458c-3535-4444-bc28-0db056f7a489)

6. Press the start button and got following errors

```
ArgumentException: Texture for property id 718 not found.
EnvironmentDepthAccess.UpdateCurrentRenderingState () (at Assets/Scripts/EnvironmentDepthAccess.cs:96)
EnvironmentDepthAccess.DispatchCompute (System.Collections.Generic.List`1[T] requestedPositions) (at Assets/Scripts/EnvironmentDepthAccess.cs:49)
EnvironmentDepthAccess.RaycastViewSpaceBlocking (UnityEngine.Vector2 viewSpaceCoord) (at Assets/Scripts/EnvironmentDepthAccess.cs:42)
DepthRaycast.Update () (at Assets/Scripts/DepthRaycast.cs:18)
```

**Comment by TudorJude** [comment]
Hello,

We really only played around with this in URP but you can try this. Replace 

```C#
_computeShader.SetMatrixArray("unity_StereoMatrixInvVP", Shader.GetGlobalMatrixArray("unity_StereoMatrixInvVP"));
```

with 

```C#
var leftEyeCamera = _cameraRig.leftEyeCamera;
var _matrixV = leftEyeCamera.GetStereoViewMatrix(Camera.StereoscopicEye.Left);
var _matrixVP = GL.GetGPUProjectionMatrix(leftEyeCamera.GetStereoProjectionMatrix(Camera.StereoscopicEye.Left), false) * _matrixV;
_computeShader.SetMatrixArray("unity_StereoMatrixInvVP", _matrixVP.inverse);
```

**Comment by QiuHong-1202** [comment]
Thanks for your relpy!

I have tried to replace the code you listed and get a complie error
```
Cannot resolve method 'SetMatrixArray(string, UnityEngine.Matrix4x4)', candidates are:   void SetMatrixArray(int, UnityEngine.Matrix4x4[]) (in class ComputeShader)   void SetMatrixArray(string, UnityEngine.Matrix4x4[]) (in class ComputeShader)
```

It seems that we should pass Matrix4x4 array not a single matrix, so I modify the code like this 

```C#
// See UniversalRenderPipelineCore for property IDs
_computeShader.SetVector("_ZBufferParams", Shader.GetGlobalVector("_ZBufferParams"));
// _computeShader.SetMatrixArray("unity_StereoMatrixInvVP", Shader.GetGlobalMatrixArray("unity_StereoMatrixInvVP"));
var leftEyeCamera = _cameraRig.leftEyeCamera;
var _matrixV = leftEyeCamera.GetStereoViewMatrix(Camera.StereoscopicEye.Left);
var _matrixVP = GL.GetGPUProjectionMatrix(leftEyeCamera.GetStereoProjectionMatrix(Camera.StereoscopicEye.Left), false) * _matrixV;
Matrix4x4[] matrixArray = new Matrix4x4[] { _matrixVP.inverse };
_computeShader.SetMatrixArray("unity_StereoMatrixInvVP", matrixArray);
```

But I still get Texture for property id not found exception
```
ArgumentException: Texture for property id 738 not found.
EnvironmentDepthAccess.UpdateCurrentRenderingState () (at Assets/Scripts/EnvironmentDepthAccess.cs:98)
EnvironmentDepthAccess.DispatchCompute (System.Collections.Generic.List`1[T] requestedPositions) (at Assets/Scripts/EnvironmentDepthAccess.cs:51)
EnvironmentDepthAccess.RaycastViewSpaceBlocking (UnityEngine.Vector2 viewSpaceCoord) (at Assets/Scripts/EnvironmentDepthAccess.cs:44)
DepthRaycast.Update () (at Assets/Scripts/DepthRaycast.cs:18)
```

Do you have any idea about this?

**Comment by QiuHong-1202** [comment]
By the way, I have just switched my project to URP, but still got texture property id 738 not found error

**Comment by TudorJude** [comment]
Do occlusions work in your project?

**Comment by QiuHong-1202** [comment]
I have tested the scripts in both the example repository and a new, clean project. Both of them work fine. Thank you for your patient guidance!

However, I still encounter an error when using this feature. Although it doesn't prevent me from obtaining the raycast result, should we address this error?

```
Compute shader (RayCast): Property (_EnvironmentDepthTexture) at kernel index (0) is not set
UnityEngine.StackTraceUtility:ExtractStackTrace ()
EnvironmentDepthAccess:DispatchCompute (System.Collections.Generic.List`1<UnityEngine.Vector2>) (at Assets/DepthAPISample/Scripts/EnvironmentDepthAccess.cs:59)
EnvironmentDepthAccess:RaycastViewSpaceBlocking (UnityEngine.Vector2) (at Assets/DepthAPISample/Scripts/EnvironmentDepthAccess.cs:42)
DepthRaycast:Update () (at Assets/DepthAPISample/Scripts/DepthRaycast.cs:18)
```

Line 59 of `EnvironmentDepthAccess.cs`
```c#
_computeShader.Dispatch(0, count, 1, 1);
```

Line 42 of `EnvironmentDepthAccess.cs`
```c#
var depthRaycastResult = DispatchCompute(new List<Vector2>() { viewSpaceCoord });
```

**Comment by QiuHong-1202** [comment]
Yes, while testing in the example repo, I use the `HandsRemoval` Scene as a testing scene.

But this error pop up when the HMD not totally starts. Is this a possible reason?

I offer whole console log following:

![image](https://github.com/user-attachments/assets/dc1c8f15-c261-4d81-b92d-065232185206)

![image](https://github.com/user-attachments/assets/efa575b6-873d-4608-89ca-e0b7df96548a)

**Comment by TudorJude** [comment]
Your script is using depth access in Update, but you're not waiting for the depth textures to arrive. They are not available immediately, it takes a few frames for them to be retrieved from the system. This explains the error. First few frames throw the error but then everything works because you do indeed have textures. To solve this you need to wait for depth textures to be available and only then run your logic in the Update function of the DepthRaycast script. The EnvironmentDepthManager script has a bool property that you can query called `IsDepthAvailable`.

**Comment by QiuHong-1202** [comment]
Thanks for your kindly explain! I will modify my code to avoid this error.

**Comment by TudorJude** [comment]
Starting with v71, we've released our official solution for depth raycasting and is part of MRUK. You can find more information on it [here](https://developers.meta.com/horizon/documentation/unity/unity-mr-utility-kit-features#environment-raycasting-beta). There's also a sample within MRUK that showcases its usage [here](https://developers.meta.com/horizon/documentation/unity/unity-mr-utility-kit-samples#environment-panel-placement).

We strongly recommend using the official solution over the solutions mentioned in this thread moving forward.
