### ISSUE TITLE
Occlusion for sprite renderer (without canvas)

### ISSUE THREAD

**Issue by Squashi11** [oculus-samples/Unity-DepthAPI#62]
Hello , is there any way to make occlusion work for standalone Sprite Renderers without a canvas? using too many canvases can be demanding . Thanks 
![image](https://github.com/user-attachments/assets/512a199c-8841-4bee-9fec-79ac96eed58d)

**Comment by TudorJude** [comment]
I would start here. [This shader](https://github.com/TwoTailsGames/Unity-Built-in-Shaders/blob/master/DefaultResourcesExtra/Sprites-Diffuse.shader) seems to be the sprite renderer shader from Unity, but I can't quite tell for sure. You can find all of Unity's shaders on github if you search for a bit.

Then, apply the shader changes as in the docs.

**Comment by Squashi11** [comment]
Hey , sorry for replying so late but the reason my occlusion didnt work was because of wrong rotation of my quad. So all good now. But a new problem I noticed started when I tried using panel for occlusion instead of a quad with a mesh collider for my raycast. The OVR Raycaster and input system for VR just doesnt work with the panel occlusion, even with raycast target turned off, it works just fine when I completely disable the panel with an occlusion material, of course I am at Unity 6 so that might be the reason for the strange behaviour

**Comment by TudorJude** [comment]
I am not that familiar with the OVR Raycaster, but does the occlusion material panel have any collider on it?

**Comment by Squashi11** [comment]
No, the panel does not have any collider attached to it. I was using quad with a mesh collider just so my custom raycast script was detecting it , the OVR Raycast does not depend on colliders as far as I know. And the canvas panel component cannot have a mesh collider attached to it as it needs a mesh to work and panel is just an UI element. Of course the panel was always at the bottom of the hierarchy for occlusion to work properly, but then the input system stopped working for some reason.

**Comment by Squashi11** [comment]
Occlusion works as expected thanks, but OVR Input System Gets blocked by a panel so I need to keep using quad
