### ISSUE TITLE
DepthAPI and MetaXR simulator v68

### ISSUE THREAD

**Issue by alfiolocastro** [oculus-samples/Unity-DepthAPI#64]
Hello,

Sorry for the delay, but I reached out to the XRSim team. It seems that starting v66, a bug was introduced, so it will not work. The fix should be arriving in a future update.

_Originally posted by @TudorJude in https://github.com/oculus-samples/Unity-DepthAPI/issues/46#issuecomment-2213274340_

**Comment by TudorJude** [comment]
Hello,

A fix was made regarding this issue and will be part of a future update of the XR Sim package. I will update this thread once that happens. I am keeping this issue open and pinned until then.

**Comment by TudorJude** [comment]
v69 has been recently released for meta sdks. XRSim v69 now works with Depth API.
