### ISSUE TITLE
Weird panel with occlusion behaviour

### ISSUE THREAD

**Issue by Squashi11** [oculus-samples/Unity-DepthAPI#66]
I am using the newest unity 6 release with the v69 DepthAPI package and the OcclusionCutoutShader from Guide. When using panel ui occlusion it behaves weirdly under certain angles (ignores image mask etc)
Below are attached photos and gifs for more info

![image](https://github.com/user-attachments/assets/db76b024-43d8-4df5-b9db-8063da3a50a6)
![Unity_cHjC2P6l5l](https://github.com/user-attachments/assets/982907c5-d5cd-49e7-bec5-c76087fecb8b)
![Unity_gp1ZnTVNgS](https://github.com/user-attachments/assets/efa12a7c-13cc-438d-a499-cb0b29541bd9)
![image](https://github.com/user-attachments/assets/eee0f796-247b-45ec-86a0-93e2b8b2063b)

**Comment by Squashi11** [comment]
This happens both in build and in editor

**Comment by TudorJude** [comment]
It's a bit hard to tell what the problem might be, try playing around with different rendering queues/ sorting queues of the mask.

**Comment by Squashi11** [comment]
I managed to fix this issue by scaling the panel dynamically and using a +100 render queue mask
