### ISSUE TITLE
Occlusion Standard Shader not rendering after first execution

### ISSUE THREAD

**Issue by DavidRainder** [oculus-samples/Unity-DepthAPI#9]
I have been experiencing this issue where I set the Occlusion Shader to any material and it doesn't render anything, except from the editor the first time I set said Shader. If I execute, nothing that holds that Shader will be rendered on the screen, neither on the Quest 3 nor in Unity. 

I also have made another project from scratch following the instructions and didn't work either. Am I missing some settings?

Unity version is: 2022.3.11f LTS
Oculus Integration SDK version is: 57.0
Rendering Pipeline is: BiRP 

I attached this video to show what I mean:

https://github.com/oculus-samples/Unity-DepthAPI/assets/91317502/f1276172-932f-4218-9a1f-4c0e1ee850ba

**Comment by TudorJude** [comment]
Hey David,

For building on the Quest 3 did you remember to call this command?
```adb shell setprop debug.oculus.experimentalEnabled 1```

Also is this the version of Oculus.XR that you have in the package manager?
```version - 4.2.0-exp-env-depth.1```

If yes, then it might be a bug and we'll have to investigate further.

It not rendering in editor is a bit strange, we haven't encountered that issue but we'll take a look. Do you use Link?

Thanks for the feedback

**Comment by DavidRainder** [comment]
> Hey David,
> 
> For building on the Quest 3 did you remember to call this command? `adb shell setprop debug.oculus.experimentalEnabled 1`
> 
> Also is this the version of Oculus.XR that you have in the package manager? `version - 4.2.0-exp-env-depth.1`
> 
> If yes, then it might be a bug and we'll have to investigate further.
> 
> It not rendering in editor is a bit strange, we haven't encountered that issue but we'll take a look. Do you use Link?
> 
> Thanks for the feedback

I have tried running the command and didn't work either. 

Yes, the Oculus.XR version I have installed is: 4.2.0-exp-env-depth.1, as can be seen on the attached screenshot. 

![image](https://github.com/oculus-samples/Unity-DepthAPI/assets/91317502/95a84cdc-62d6-43a7-a0d4-ea97aae2ff68)

**Comment by TudorJude** [comment]
A fix will land soon for the issue where these materials don't render in the editor. As for occlusions not showing on your device that's a different issue. Could you please build on device again and send me a log from adb?

**Comment by DavidRainder** [comment]
It's funny, I did build again in order to get the log, but now it actually works on build. I may probably have been missing some setup settings, I really do not remember if I've changed something. 
I'm glad that you have found the key to the issue! And thanks for the quick response and support!

**Comment by TudorJude** [comment]
Glad it worked. Keep in mind, this is still an ongoing feature and any feedback from your is greatly appreciated. Closing the issue.
